export const LOGIN_REQUEST = "login_request";
export const LOGIN_SUCCESS = "login_success";
export const LOGIN_FAILURE = "login_failure";

export const LOAD_USER_REQUEST = "load_user_request";
export const LOAD_USER_SUCCESS = "load_user_success";
export const LOAD_USER_FAIL = "load_user_failure";

export const LOGOUT_SUCCESS = "logout_success";
export const LOGOUT_FAILURE = "logout_failure";

export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_FAILURE = "FETCH_CUSTOMER_FAILURE";
export const FETCH_CUSTOMER_REQUEST = "FETCH_CUSTOMER_REQUEST";
export const CLEAR_ERRORS_FETCH_CUSTOMER = "CLEAR_ERRORS_FETCH_CUSTOMER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";

export const CREATE_REPORT_TYPE_REQUEST = "CREATE_REPORT_TYPE_REQUEST";
export const CREATE_REPORT_TYPE_SUCCESS = "CREATE_REPORT_TYPE_SUCCESS";
export const CREATE_REPORT_TYPE_FAIL = "CREATE_REPORT_TYPE_FAIL";
export const CLEAR_ERROR_REPORT_TYPE = "CLEAR_ERROR_REPORT_TYPE";
export const RESET_CREATE_REPORT_TYPE = "RESET_CREATE_REPORT_TYPE";

export const GET_ALL_REPORTS_TYPE_REQUEST = "GET_ALL_REPORTS_TYPE_REQUEST";
export const GET_ALL_REPORTS_TYPE_SUCCES = "GET_ALL_REPORTS_TYPE_SUCCES";
export const GET_ALL_REPORTS_TYPE_ERROR = "GET_ALL_REPORTS_TYPE_ERROR";
export const CLEAR_ERROR_GET_ALL_REPORTS_TYPE = "CLEART_GET_ALL_REPORTS_TYPE";

export const GET_REPORT_TYPE_REQUEST = "GET_REPORT_TYPE_REQUEST";
export const GET_REPORT_TYPE_SUCCESS = "GET_REPORT_TYPE_SUCCESS";
export const GET_REPORT_TYPE_ERROR = "GET_REPORT_TYPE_ERROR";
export const CLEAR_ERROR_GET_REPORT_TYPE = "CLEAR_ERROR_GET_REPORT_TYPE";

export const UPDATE_REPORT_TYPE_REQUEST = "UPDATE_REPORT_TYPE_REQUEST";
export const UPDATE_REPORT_TYPE_SUCCESS = "UPDATE_REPORT_TYPE_SUCCESS";
export const UPDATE_REPORT_TYPE_ERROR = "UPDATE_REPORT_TYPE_ERROR";
export const CLEAR_UPDATE_REPORT_TYPE = "CLEAR_UPDATE_REPORT_TYPE";
export const RESET_UPDATE_REPORT_TYPE = "RESET_UPDATE_REPORT_TYPE";

export const GET_ALL_DATA_REQUEST = "GET_ALL_DATA_REQUEST";
export const GET_ALL_DATA_SUCCES = "GET_ALL_DATA_SUCCES";
export const GET_ALL_DATA_ERROR = "GET_ALL_DATA_ERROR";
export const CLEAR_ALL_DATA_ERROR = "CLEAR_ALL_DATA_ERROR";

export const CREATE_CATEGORY_STREAM_REQEST = "CREATE_CATEGORY_STREAM_REQEST";
export const CREATE_CATEGORY_STREAM_SUCCESS = "CREATE_CATEGORY_STREAM_SUCCESS";
export const CREATE_CATEGORY_STREAM_ERROR = "CREATE_CATEGORY_STREAM_ERROR";
export const CLEAR_CREATE_CATEGORY_STREAM_ERROR = "CLEAR_CREATE_CATEGORY_STREAM_ERROR";
export const RESET_CREATE_CATEGORY_STREAM = "RESET_CREATE_CATEGORY_STREAM";

export const GET_ALL_CATEGORY_STREAN_REQUEST = "GET_ALL_CATEGORY_STREAN_REQUEST";
export const GET_ALL_CATEGORY_STREAN_SUCCESS = "GET_ALL_CATEGORY_STREAN_SUCCESS";
export const GET_ALL_CATEGORY_STREAN_FAILURE = "GET_ALL_CATEGORY_STREAN_FAIL";
export const CLEAR_GET_ALL_CATEGORY_STREAM_FAILURE = "CLEAR_GET_ALL_CATEGORY_STREAM_FAILURE";

export const GET_CATEGORY_STREAM_REQUUEST = "GET_CATEGORY_STREAM_REQUUEST";
export const GET_CATEGORY_STREAM_SUCCESS = "GET_CATEGORY_STREAM_SUCCESS";
export const GET_CATEGORY_STREAM_FAILURE = "GET_CATEGORY_STREAM_FAILURE";
export const CLEAR_GET_CATEGORY_STREAM_FAILURE = "CLEAR_GET_CATEGORY_STREAM_FAILURE";

export const UPDATE_CATEGORY_STREAM_REQEST = "UPDATE_CATEGORY_STREAM_REQEST";
export const UPDATE_CATEGORY_STREAM_SUCCESS = "UPDATE_CATEGORY_STREAM_SUCCESS";
export const UPDATE_CATEGORY_STREAM_FAILURE = "UPDATE_CATEGORY_STREAM_FAILURE";
export const CLEAR_UPDATE_CATEGORY_STREAM = "CLEAR_UPDATE_CATEGORY_STREAM";
export const RESET_UPDATE_CATEGORY_STREAM = "RESET_UPDATE_CATEGORY_STREAM";

// TODO: CREATE CONSTANTS POST

export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAIL = "GET_ALL_POST_FAIL";
export const CLEAR_GET_ALL_POST_FAIL = "CLEAR_GET_ALL_POST_FAIL";

export const GET_ONE_POST_REQUES = "GET_ONE_POST_REQUES";
export const GET_ONE_POST_SUCCES = "GET_ONE_POST_SUCCES";
export const GET_ONE_POST_FUILURE = "GET_ONE_POST_FUILURE";
export const CLEAR_GET_ONE_POST_FAILURE = "CLEAR_GET_ONE_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FUILURE = "UPDATE_POST_FUILURE";
export const CLEAR_UPDATE_POST_FAUILURE = "CLEAR_UPDATE_POST_FAILURE";
export const RESET_UPDATE_POST = "RESET_UPDATE_POST";

export const TOGGLE_POST_PUBLIC_REQUEST = "TOGGLE_POST_PUBLIC_REQUEST";
export const TOGGLE_POST_PUBLIC_SUCCESS = "TOGGLE_POST_PUBLIC_SUCCESS";
export const TOGGLE_POST_PUBLIC_ERROR = "TOGGLE_POST_PUBLIC_ERROR";
export const CLEAR_TOGGLE_POST_PUBLIC_ERROR = "CLEAR_TOGGLE_POST_PUBLIC_ERROR";
export const RESET_TOGGLE_POST_PUBLIC_SUCCESS = "RESET_TOGGLE_POST_PUBLIC_SUCCESS";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
export const CLEAR_DELETE_POST_ERROR = "CLEAR_DELETE_POST_ERROR";

// TODO:CATEGORY_POST

export const CREATE_CATEGORY_POST_REQUEST = "CREATE_CATEGORY_POST_REQUEST";
export const CREATE_CATEGORY_POST_SUCCESS = "CREATE_CATEGORY_POST_SUCCESS";
export const CREATE_CATEGORY_POST_FAIL = "CREATE_CATEGORY_POST_FAIL";
export const CLEAR_CREATE_CATEGORY_POST_FAIL = "CLEAR_CREATE_CATEGORY_POST_FAIL";
export const RESET_CREATE_CATEGORY_POST = "RESET_CREATE_CATEGORY_POST";

export const GET_ALL_CATEGORY_POST_REQUEST = "GET_ALL_CATEGORY_POST_REQUEST";
export const GET_ALL_CATEGORY_POST_SUCCESS = "GET_ALL_CATEGORY_POST_SUCCESS";
export const GET_ALL_CATEGORY_POST_ERROR = "GET_ALL_CATEGORY_POST_ERROR";
export const CLEAR_GET_ALL_CATEGORY_POST_ERROR = "CLEAR_GET_ALL_CATEGORY_POST_ERROR";

export const GET_CATEGORY_POST_REQUEST = "GET_CATEGORY_POST_REQUEST";
export const GET_CATEGORY_POST_SUCCESS = "GET_CATEGORY_POST_SUCCESS";
export const GET_CATEGORY_POST_ERRROR = "GET_CATEGORY_POST_ERRROR";
export const CLEAR_GET_CATEGORY_POST_ERRROR = "CLEAR_GET_CATEGORY_POST_ERRROR";

export const UPDATE_CATEGORY_POST_REQUEST = "UPDATE_CATEGORY_POST_REQUEST";
export const UPDATE_CATEGORY_POST_SUCCESS = "UPDATE_CATEGORY_POST_SUCCESS";
export const UPDATE_CATEGORY_POST_ERROR = "UPDATE_CATEGORY_POST_ERROR";
export const CLEAR_UPDATE_CATGEORY_POST_ERROR = "CLEAR_UPDATE_CATGEORY_POST_ERROR";
export const RESET_UPDATE_CATEGORY_POST = "RESET_UPDATE_CATEGORY_POST";

// TODO: CREATE CONSTANTS REDUX CUSTOMER

export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAILER = "GET_CUSTOMER_FAILER";
export const CLEAR_GET_CUSTOMER_FAILER = "CLEAR_GET_CUSTOMER_FAILER";

export const GET_ALL_STREAMMER_REQUEST = "GET_ALL_STREAMMER_REQUEST";
export const GET_ALL_STREAMMER_SUCCESS = "GET_ALL_STREAMMER_SUCCESS";
export const GET_ALL_STREAMMER_FAILURE = "GET_ALL_STREAMMER_FAILURE";
export const CLEAR_ALL_STREAMMER_FAILURE = "CLEAR_ALL_STREAMMER_FAILURE";

// POST
export const GET_POST_REQUEST = "GET_POSTS_REQUESR";
export const GET_POST_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POST_ERROR = "GET_POSTS_ERROR";
export const CLEAR_GET_POST_ERROR = "CLEAR_GET_POSTS_ERROR";

// POST
export const GET_STREAMS_REQUEST = "GET_STREAMSS_REQUESR";
export const GET_STREAMS_SUCCESS = "GET_STREAMSS_SUCCESS";
export const GET_STREAMS_ERROR = "GET_STREAMSS_ERROR";
export const CLEAR_GET_STREAMS_ERROR = "CLEAR_GET_STREAMSS_ERROR";

export const GET_STREAM_REQUEST = "GET_STREAMS_REQUESR";
export const GET_STREAM_SUCCESS = "GET_STREAMS_SUCCESS";
export const GET_STREAM_ERROR = "GET_STREAMS_ERROR";
export const CLEAR_GET_STREAM_ERROR = "CLEAR_GET_STREAMS_ERROR";

// VIDEOS
export const GET_VIDEOS_REQUEST = "GET_VIDEOSS_REQUESR";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOSS_SUCCESS";
export const GET_VIDEOS_ERROR = "GET_VIDEOSS_ERROR";
export const CLEAR_GET_VIDEOS_ERROR = "CLEAR_GET_VIDEOSS_ERROR";

export const GET_VIDEO_REQUEST = "GET_VIDEOS_REQUESR";
export const GET_VIDEO_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEO_ERROR = "GET_VIDEOS_ERROR";
export const CLEAR_GET_VIDEO_ERROR = "CLEAR_GET_VIDEOS_ERROR";

/// REPORT TYPES POST
export const CREATE_REPORT_TYPE_POST_REQUEST = "CREATE_REPORT_TYPE_POST_REQUEST";
export const CREATE_REPORT_TYPE_POST_SUCCESS = "CREATE_REPORT_TYPE_POST_SUCCESS";
export const CREATE_REPORT_TYPE_POST_FAIL = "CREATE_REPORT_TYPE_POST_FAIL";
export const CLEAR_ERROR_REPORT_TYPE_POST = "CLEAR_ERROR_REPORT_TYPE_POST";
export const RESET_CREATE_REPORT_TYPE_POST = "RESET_CREATE_REPORT_TYPE_POST";

export const GET_ALL_REPORTS_TYPE_POST_REQUEST = "GET_ALL_REPORTS_TYPE_POST_REQUEST";
export const GET_ALL_REPORTS_TYPE_POST_SUCCES = "GET_ALL_REPORTS_TYPE_POST_SUCCES";
export const GET_ALL_REPORTS_TYPE_POST_ERROR = "GET_ALL_REPORTS_TYPE_POST_ERROR";
export const CLEAR_ERROR_GET_ALL_REPORTS_TYPE_POST = "CLEART_GET_ALL_REPORTS_TYPE_POST";

export const GET_REPORT_TYPE_POST_REQUEST = "GET_REPORT_TYPE_POST_REQUEST";
export const GET_REPORT_TYPE_POST_SUCCESS = "GET_REPORT_TYPE_POST_SUCCESS";
export const GET_REPORT_TYPE_POST_ERROR = "GET_REPORT_TYPE_POST_ERROR";
export const CLEAR_ERROR_GET_REPORT_TYPE_POST = "CLEAR_ERROR_GET_REPORT_TYPE_POST";

export const UPDATE_REPORT_TYPE_POST_REQUEST = "UPDATE_REPORT_TYPE_POST_REQUEST";
export const UPDATE_REPORT_TYPE_POST_SUCCESS = "UPDATE_REPORT_TYPE_POST_SUCCESS";
export const UPDATE_REPORT_TYPE_POST_ERROR = "UPDATE_REPORT_TYPE_POST_ERROR";
export const CLEAR_UPDATE_REPORT_TYPE_POST = "CLEAR_UPDATE_REPORT_TYPE_POST";
export const RESET_UPDATE_REPORT_TYPE_POST = "RESET_UPDATE_REPORT_TYPE_POST";

/// REPORT _ POST
export const GET_ALL_REPORT_POST_REQUEST = "GET_ALL_REPORT_POST_REQUEST";
export const GET_ALL_REPORT_POST_SUCCESS = "GET_ALL_REPORT_POST_SUCCESS";
export const GET_ALL_REPORT_POST_ERROR = "GET_ALL_REPORT_POST_ERROR";
export const CLEAR_GET_ALL_REPORT_POST_ERROR = "CLEAR_GET_ALL_REPORT_POST_ERROR";

export const GET_REPORT_POST_REQUEST = "GET_REPORT_POST_REQUEST";
export const GET_REPORT_POST_SUCCESS = "GET_REPORT_POST_SUCCESS";
export const GET_REPORT_POST_ERROR = "GET_REPORT_POST_ERROR";
export const CLEAR_GET_REPORT_POST_ERROR = "CLEAR_GET_REPORT_POST_ERROR";

// REPORT_STREAM

// REPORT
export const GET_ALL_REPORT_STREAM_REQUEST = "GET_ALL_REPORT_STREAM_REQUEST";
export const GET_ALL_REPORT_STREAM_SUCCESS = "GET_ALL_REPORT_STREAM_SUCCESS";
export const GET_ALL_REPORT_STREAM_ERROR = "GET_ALL_REPORT_STREAM_ERROR";
export const CLEAR_GET_ALL_REPORT_STREAM_ERROR = "CLEAR_GET_ALL_REPORT_STREAM_ERROR";

export const GET_REPORT_STREAM_REQUEST = "GET_REPORT_STREAM_REQUEST";
export const GET_REPORT_STREAM_SUCCESS = "GET_REPORT_STREAM_SUCCESS";
export const GET_REPORT_STREAM_ERROR = "GET_REPORT_STREAM_ERROR";
export const CLEAR_GET_REPORT_STREAM_ERROR = "CLEAR_GET_REPORT_STREAM_ERROR";

// Log history

export const GET_ALL_LOG_HISTORY_REQUEST = "GET_ALL_LOG_HISTORY_REQUEST";
export const GET_ALL_LOG_HISTORY_SUCCESS = "GET_ALL_LOG_HISTORY_SUCCESS";
export const GET_ALL_LOG_HISTORY_ERROR = "GET_ALL_LOG_HISTORY_ERROR";
export const CLEAR_GET_ALL_LOG_HISTORY_ERROR = "CLEAR_GET_ALL_LOG_HISTORY_ERROR";

export const GET_LOG_HISTORY_REQUEST = "GET_LOG_HISTORY_REQUEST";
export const GET_LOG_HISTORY_SUCCESS = "GET_LOG_HISTORY_SUCCESS";
export const GET_LOG_HISTORY_ERROR = "GET_LOG_HISTORY_ERROR";
export const CLEAR_GET_LOG_HISTORY_ERROR = "CLEAR_GET_LOG_HISTORY_ERROR";

export const DELETE_LOG_HISTORY_REQUEST = "DELETE_LOG_HISTORY_REQUEST";
export const DELETE_LOG_HISTORY_SUCCESS = "DELETE_LOG_HISTORY_SUCCESS";
export const DELETE_LOG_HISTORY_ERROR = "DELETE_LOG_HISTORY_ERROR";
export const CLEAR_DELETE_LOG_HISTORY_ERROR = "CLEAR_DELETE_LOG_HISTORY_ERROR";
