export const LOGIN_REQUEST = "login_request";
export const LOGIN_SUCCESS = "login_success";
export const LOGIN_FAILURE = "login_failure";

export const LOAD_USER_REQUEST = "load_user_request";
export const LOAD_USER_SUCCESS = "load_user_success";
export const LOAD_USER_FAIL = "load_user_failure";

export const LOGOUT_SUCCESS = "logout_success";
export const LOGOUT_FAILURE = "logout_failure";

export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_FAILURE = "FETCH_CUSTOMER_FAILURE";
export const FETCH_CUSTOMER_REQUEST = "FETCH_CUSTOMER_REQUEST";
export const CLEAR_ERRORS_FETCH_CUSTOMER = "CLEAR_ERRORS_FETCH_CUSTOMER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";

export const CREATE_REPORT_TYPE_REQUEST = "CREATE_REPORT_TYPE_REQUEST";
export const CREATE_REPORT_TYPE_SUCCESS = "CREATE_REPORT_TYPE_SUCCESS";
export const CREATE_REPORT_TYPE_FAIL = "CREATE_REPORT_TYPE_FAIL";
export const CLEAR_ERROR_REPORT_TYPE = "CLEAR_ERROR_REPORT_TYPE";
export const RESET_CREATE_REPORT_TYPE = "RESET_CREATE_REPORT_TYPE";

export const GET_ALL_REPORTS_TYPE_REQUEST = "GET_ALL_REPORTS_TYPE_REQUEST";
export const GET_ALL_REPORTS_TYPE_SUCCES = "GET_ALL_REPORTS_TYPE_SUCCES";
export const GET_ALL_REPORTS_TYPE_ERROR = "GET_ALL_REPORTS_TYPE_ERROR";
export const CLEAR_ERROR_GET_ALL_REPORTS_TYPE = "CLEART_GET_ALL_REPORTS_TYPE";

export const GET_REPORT_TYPE_REQUEST = "GET_REPORT_TYPE_REQUEST";
export const GET_REPORT_TYPE_SUCCESS = "GET_REPORT_TYPE_SUCCESS";
export const GET_REPORT_TYPE_ERROR = "GET_REPORT_TYPE_ERROR";
export const CLEAR_ERROR_GET_REPORT_TYPE = "CLEAR_ERROR_GET_REPORT_TYPE";

export const UPDATE_REPORT_TYPE_REQUEST = "UPDATE_REPORT_TYPE_REQUEST";
export const UPDATE_REPORT_TYPE_SUCCESS = "UPDATE_REPORT_TYPE_SUCCESS";
export const UPDATE_REPORT_TYPE_ERROR = "UPDATE_REPORT_TYPE_ERROR";
export const CLEAR_UPDATE_REPORT_TYPE = "CLEAR_UPDATE_REPORT_TYPE";
export const RESET_UPDATE_REPORT_TYPE = "RESET_UPDATE_REPORT_TYPE";

export const GET_ALL_DATA_REQUEST = "GET_ALL_DATA_REQUEST";
export const GET_ALL_DATA_SUCCES = "GET_ALL_DATA_SUCCES";
export const GET_ALL_DATA_ERROR = "GET_ALL_DATA_ERROR";
export const CLEAR_ALL_DATA_ERROR = "CLEAR_ALL_DATA_ERROR";

export const CREATE_CATEGORY_STREAM_REQEST = "CREATE_CATEGORY_STREAM_REQEST";
export const CREATE_CATEGORY_STREAM_SUCCESS = "CREATE_CATEGORY_STREAM_SUCCESS";
export const CREATE_CATEGORY_STREAM_ERROR = "CREATE_CATEGORY_STREAM_ERROR";
export const CLEAR_CREATE_CATEGORY_STREAM_ERROR = "CLEAR_CREATE_CATEGORY_STREAM_ERROR";
export const RESET_CREATE_CATEGORY_STREAM = "RESET_CREATE_CATEGORY_STREAM";

export const GET_ALL_CATEGORY_STREAN_REQUEST = "GET_ALL_CATEGORY_STREAN_REQUEST";
export const GET_ALL_CATEGORY_STREAN_SUCCESS = "GET_ALL_CATEGORY_STREAN_SUCCESS";
export const GET_ALL_CATEGORY_STREAN_FAILURE = "GET_ALL_CATEGORY_STREAN_FAIL";
export const CLEAR_GET_ALL_CATEGORY_STREAM_FAILURE = "CLEAR_GET_ALL_CATEGORY_STREAM_FAILURE";

export const GET_CATEGORY_STREAM_REQUUEST = "GET_CATEGORY_STREAM_REQUUEST";
export const GET_CATEGORY_STREAM_SUCCESS = "GET_CATEGORY_STREAM_SUCCESS";
export const GET_CATEGORY_STREAM_FAILURE = "GET_CATEGORY_STREAM_FAILURE";
export const CLEAR_GET_CATEGORY_STREAM_FAILURE = "CLEAR_GET_CATEGORY_STREAM_FAILURE";

export const UPDATE_CATEGORY_STREAM_REQEST = "UPDATE_CATEGORY_STREAM_REQEST";
export const UPDATE_CATEGORY_STREAM_SUCCESS = "UPDATE_CATEGORY_STREAM_SUCCESS";
export const UPDATE_CATEGORY_STREAM_FAILURE = "UPDATE_CATEGORY_STREAM_FAILURE";
export const CLEAR_UPDATE_CATEGORY_STREAM = "CLEAR_UPDATE_CATEGORY_STREAM";
export const RESET_UPDATE_CATEGORY_STREAM = "RESET_UPDATE_CATEGORY_STREAM";

// TODO: CREATE CONSTANTS POST

export const CREATE_CATEGORY_POST_REQUEST = "CREATE_CATEGORY_POST_REQUEST";
export const CREATE_CATEGORY_POST_SUCCESS = "CREATE_CATEGORY_POST_SUCCESS";
export const CREATE_CATEGORY_POST_FAIL = "CREATE_CATEGORY_POST_FAIL";
export const CLEAR_CREATE_CATEGORY_POST_FAIL = "CLEAR_CREATE_CATEGORY_POST_FAIL";
export const RESET_CREATE_CATEGORY_POST = "RESET_CREATE_CATEGORY_POST";

export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAIL = "GET_ALL_POST_FAIL";
export const CLEAR_GET_ALL_POST_FAIL = "CLEAR_GET_ALL_POST_FAIL";

// TODO: CREATE CONSTANTS REDUX CUSTOMER

export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAILER = "GET_CUSTOMER_FAILER";
export const CLEAR_GET_CUSTOMER_FAILER = "CLEAR_GET_CUSTOMER_FAILER";
